### PR TITLE
Comment out descriptions  Update bug_report.md 

### PR DESCRIPTION
**Pull request by prykdev**
### Description

Fixes #ISSUE_NUMBER

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by epicadk** [comment]
Yes you are on the right track. Please comment out the other subheadings too.

**Comment by prykdev** [comment]
Is it now done? or anything else i need to change to get it merged ?

**Comment by epicadk** [comment]
> Is it now done? or anything else i need to change to get it merged ?

Take a look at the other files too. They need to be commented out too. This file is done : ).

**Comment by prykdev** [comment]
Done now?
Thanks for helping out.

**Review by epicadk — APPROVED** [review]
💯 Thankyou for your contribution

**Comment by prykdev** [comment]
Thank You so much for guiding. I have a small doubt that do i need to register for contributing in OSH (ie) starting from April?

**Comment by epicadk** [comment]
> Thank You so much for guiding. I have a small doubt that do i need to register for contributing in OSH (ie) starting from march ?

Nope. No need to register. You can directly pickup issues in BIT and Stem diverse tv.

**Review by isabelcosta — APPROVED** [review]

**Comment by isabelcosta** [comment]
Thank you for your contribution @P-riyanka-prasad 🎉

**Pull request merged**
